server:
  port: 8080
  servlet:
    context-path: /api

application:
  title: Spring Boot + Elastic Stack
  version: 0.0.1-SNAPSHOT

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/elasticstack?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false}
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    username: ${SPRING_DATASOURCE_USERNAME:elasticstack}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}

elasticsearch:
  cluster-name: spring-boot-cluster
  host: localhost
  port: 9300

logging:
  file: /Users/kaanalkim/Documents/Development/logs/app.log

